# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1430750938);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.6.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"messagingmenu@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"mtime\":1427755282000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1430148476000,\"rdfTime\":1427754626000}}}]");
user_pref("extensions.lastAppVersion", "31.6.0");
user_pref("extensions.lastPlatformVersion", "31.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.ui-rdf.version", 5);
user_pref("mailnews.database.global.datastore.id", "c7c6ebd4-40f0-4ca1-b349-66ff41c4754");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("toolkit.telemetry.previousBuildID", "20150330214959");
