# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1431611267);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1431611387);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1431614507);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1431611147);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1431611027);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.countryCode", "ZA");
user_pref("browser.search.region", "ZA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150417180217");
user_pref("browser.slowStartup.averageTime", 4257);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20150417180217");
user_pref("browser.startup.homepage_override.mstone", "37.0.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1431615412951");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1431615412350");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1430812315070");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1431701812951");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1430207981865");
user_pref("datareporting.policy.firstRunTime", "1430207917901");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 3951);
user_pref("datareporting.sessions.current.main", 1081);
user_pref("datareporting.sessions.current.sessionRestored", 4273);
user_pref("datareporting.sessions.current.startTime", "1431610784475");
user_pref("datareporting.sessions.current.totalTime", 7203);
user_pref("datareporting.sessions.currentIndex", 10);
user_pref("datareporting.sessions.prunedIndex", 9);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"37.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"37.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.0,%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2014.08.06.beta,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:37.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1430818458);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150311.01");
user_pref("extensions.lastAppVersion", "37.0.2");
user_pref("extensions.lastPlatformVersion", "37.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"37.0.2\",\"st\":1429295548000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"37.0.2\",\"st\":1429295548000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"37.0.2\",\"st\":1430148342000,\"mt\":1429294943000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1430148500000,\"mt\":1420839872000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"e\":true,\"v\":\"2014.08.06.beta\",\"st\":1430148503000,\"mt\":1407283796000},\"webapps-team@lists.launchpad.net\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"e\":true,\"v\":\"3.0.2\",\"st\":1397697896000,\"mt\":1397665356000}},\"app-system-local\":{\"online-accounts@lists.launchpad.net\":{\"d\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"e\":true,\"v\":\"0.5\",\"st\":1397697896000,\"mt\":1390969548000}}}");
user_pref("gecko.buildID", "20150417180217");
user_pref("gecko.mstone", "37.0.2");
user_pref("idle.lastDailyNotification", 1431611407);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1430208170);
user_pref("media.gmp-gmpopenh264.version", "1.3");
user_pref("media.gmp-manager.lastCheck", 1430812313);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1431610849);
user_pref("places.history.expiration.transient_current_max_pages", 101200);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1430208406);
user_pref("toolkit.startup.last_success", 1431610785);
user_pref("toolkit.telemetry.previousBuildID", "20150417180217");
